server:
  port: 2222

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://116.178.87.242:3306/xjyq
    username: root
    password: wiseweb@180420
    hikari:
      minimum-idle: 5
      idle-timeout: 30000
      maximum-pool-size: 10
      auto-commit: true
      pool-name: YoungHikariConnectionPool
      max-lifetime: 55000
      connection-timeout: 0
      connection-test-query: SELECT 1



knife4j:
  enable: false
  setting:
    enableOpenApi: false
    enableHost: true
    enableDocumentManage: false

springfox:
  documentation:
    enabled: false
